/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expendedora.efecto;

/**
 *
 * @author crist
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btncreditos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnpulseras = new javax.swing.JButton();
        btncomidaperro = new javax.swing.JButton();
        btnvinos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesventanap/dfsdf.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 550, 150));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncreditos.setText("Créditos");
        btncreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreditosActionPerformed(evt);
            }
        });
        jPanel1.add(btncreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 0, 140, 1320));

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));

        btnpulseras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpulseras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/joyeria.png"))); // NOI18N
        btnpulseras.setText("Comprar pulseras a la ultima moda");
        btnpulseras.setBorder(null);
        btnpulseras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpulseras.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnpulseras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpulserasActionPerformed(evt);
            }
        });

        btncomidaperro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncomidaperro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perro.png"))); // NOI18N
        btncomidaperro.setText("Comprar comida para mascotas");
        btncomidaperro.setBorder(null);
        btncomidaperro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncomidaperro.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btncomidaperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomidaperroActionPerformed(evt);
            }
        });

        btnvinos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnvinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banner-vino-plano_23-2148057972.png"))); // NOI18N
        btnvinos.setText("Comprar vino de la mejor calidad");
        btnvinos.setBorder(null);
        btnvinos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvinos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnvinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvinosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnvinos, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncomidaperro, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpulseras, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btncomidaperro)
                .addGap(37, 37, 37)
                .addComponent(btnvinos)
                .addGap(77, 77, 77)
                .addComponent(btnpulseras)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 550, 1160));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 1320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvinosActionPerformed
        
        Efecto e=new Efecto();
        e.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnvinosActionPerformed

    private void btncreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreditosActionPerformed
        
        creditos b=new creditos();
        b.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_btncreditosActionPerformed

    private void btncomidaperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomidaperroActionPerformed
        comidaanimal e=new comidaanimal();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncomidaperroActionPerformed

    private void btnpulserasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpulserasActionPerformed
        joyeria e=new joyeria();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnpulserasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncomidaperro;
    private javax.swing.JButton btncreditos;
    private javax.swing.JButton btnpulseras;
    private javax.swing.JButton btnvinos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
